# Generated by Django 4.1.7 on 2023-06-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0004_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
