# Generated by Django 4.1.7 on 2023-06-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0005_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
            ],
        ),
    ]
