# Generated by Django 4.1.7 on 2023-06-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0006_parameters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpCenter',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
