# Generated by Django 4.1.7 on 2023-06-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0007_delete_helpcenter_delete_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
