# Generated by Django 4.1.7 on 2023-06-11 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0009_alter_faq_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='date',
        ),
    ]
