# Generated by Django 4.1.7 on 2023-06-11 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0010_remove_faq_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
